// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dik.roo.collmate.web;

import dik.roo.collmate.domain.dod.CdFactory;
import dik.roo.collmate.service.api.CdService;
import dik.roo.collmate.web.CdsCollectionJsonController;
import dik.roo.collmate.web.CdsCollectionJsonControllerIT;
import io.springlets.boot.test.autoconfigure.web.servlet.SpringletsWebMvcTest;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.test.web.servlet.MockMvc;

privileged aspect CdsCollectionJsonControllerIT_Roo_JsonControllerIntegrationTest {
    
    declare @type: CdsCollectionJsonControllerIT: @RunWith(SpringRunner.class);
    
    declare @type: CdsCollectionJsonControllerIT: @SpringletsWebMvcTest(controllers = CdsCollectionJsonController.class, secure = false);
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @Autowired
    private MockMvc CdsCollectionJsonControllerIT.mvc;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @MockBean
    private CdService CdsCollectionJsonControllerIT.cdService;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private CdFactory CdsCollectionJsonControllerIT.factory = new CdFactory();
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return MockMvc
     */
    public MockMvc CdsCollectionJsonControllerIT.getMvc() {
        return mvc;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return CdService
     */
    public CdService CdsCollectionJsonControllerIT.getCdService() {
        return cdService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param cdService
     */
    public void CdsCollectionJsonControllerIT.setCdService(CdService cdService) {
        this.cdService = cdService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return CdFactory
     */
    public CdFactory CdsCollectionJsonControllerIT.getFactory() {
        return factory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param factory
     */
    public void CdsCollectionJsonControllerIT.setFactory(CdFactory factory) {
        this.factory = factory;
    }
    
    /**
     * Test method example. To be implemented by developer.
     * 
     */
    @Test
    public void CdsCollectionJsonControllerIT.testMethodExample() {
        // Setup
        // Previous tasks
        
        // Exercise
        // Execute method to test
        
        // Verify
        // Check results with assertions
    }
    
}
