// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dik.roo.collmate.web;

import dik.roo.collmate.domain.dod.DvdFactory;
import dik.roo.collmate.service.api.DvdService;
import dik.roo.collmate.web.DvdsCollectionThymeleafController;
import dik.roo.collmate.web.DvdsCollectionThymeleafControllerIT;
import io.springlets.boot.test.autoconfigure.web.servlet.SpringletsWebMvcTest;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.test.web.servlet.MockMvc;

privileged aspect DvdsCollectionThymeleafControllerIT_Roo_ThymeleafControllerIntegrationTest {
    
    declare @type: DvdsCollectionThymeleafControllerIT: @RunWith(SpringRunner.class);
    
    declare @type: DvdsCollectionThymeleafControllerIT: @SpringletsWebMvcTest(controllers = DvdsCollectionThymeleafController.class, secure = false);
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @Autowired
    public MockMvc DvdsCollectionThymeleafControllerIT.mvc;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @MockBean
    public DvdService DvdsCollectionThymeleafControllerIT.dvdServiceService;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public DvdFactory DvdsCollectionThymeleafControllerIT.factory = new DvdFactory();
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return MockMvc
     */
    public MockMvc DvdsCollectionThymeleafControllerIT.getMvc() {
        return mvc;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return DvdService
     */
    public DvdService DvdsCollectionThymeleafControllerIT.getDvdServiceService() {
        return dvdServiceService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return DvdFactory
     */
    public DvdFactory DvdsCollectionThymeleafControllerIT.getFactory() {
        return factory;
    }
    
    /**
     * Test method example. To be implemented by developer.
     * 
     */
    @Test
    public void DvdsCollectionThymeleafControllerIT.testMethodExample() {
        // Setup
        // Previous tasks
        
        // Exercise
        // Execute method to test
        
        // Verify
        // Check results with assertions
    }
    
}
