// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dik.roo.collmate.web;

import dik.roo.collmate.domain.dod.DvdFactory;
import dik.roo.collmate.service.api.DvdService;
import dik.roo.collmate.web.DvdsCollectionJsonController;
import dik.roo.collmate.web.DvdsCollectionJsonControllerIT;
import io.springlets.boot.test.autoconfigure.web.servlet.SpringletsWebMvcTest;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.test.web.servlet.MockMvc;

privileged aspect DvdsCollectionJsonControllerIT_Roo_JsonControllerIntegrationTest {
    
    declare @type: DvdsCollectionJsonControllerIT: @RunWith(SpringRunner.class);
    
    declare @type: DvdsCollectionJsonControllerIT: @SpringletsWebMvcTest(controllers = DvdsCollectionJsonController.class, secure = false);
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @Autowired
    private MockMvc DvdsCollectionJsonControllerIT.mvc;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @MockBean
    private DvdService DvdsCollectionJsonControllerIT.dvdService;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private DvdFactory DvdsCollectionJsonControllerIT.factory = new DvdFactory();
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return MockMvc
     */
    public MockMvc DvdsCollectionJsonControllerIT.getMvc() {
        return mvc;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return DvdService
     */
    public DvdService DvdsCollectionJsonControllerIT.getDvdService() {
        return dvdService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param dvdService
     */
    public void DvdsCollectionJsonControllerIT.setDvdService(DvdService dvdService) {
        this.dvdService = dvdService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return DvdFactory
     */
    public DvdFactory DvdsCollectionJsonControllerIT.getFactory() {
        return factory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param factory
     */
    public void DvdsCollectionJsonControllerIT.setFactory(DvdFactory factory) {
        this.factory = factory;
    }
    
    /**
     * Test method example. To be implemented by developer.
     * 
     */
    @Test
    public void DvdsCollectionJsonControllerIT.testMethodExample() {
        // Setup
        // Previous tasks
        
        // Exercise
        // Execute method to test
        
        // Verify
        // Check results with assertions
    }
    
}
