// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dik.roo.collmate.web;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.ObjectCodec;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import dik.roo.collmate.domain.Cd;
import dik.roo.collmate.service.api.CdService;
import dik.roo.collmate.web.CdDeserializer;
import io.springlets.web.NotFoundException;
import java.io.IOException;
import org.springframework.boot.jackson.JsonComponent;
import org.springframework.core.convert.ConversionService;

privileged aspect CdDeserializer_Roo_EntityDeserializer {
    
    declare @type: CdDeserializer: @JsonComponent;
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return CdService
     */
    public CdService CdDeserializer.getCdService() {
        return cdService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param cdService
     */
    public void CdDeserializer.setCdService(CdService cdService) {
        this.cdService = cdService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return ConversionService
     */
    public ConversionService CdDeserializer.getConversionService() {
        return conversionService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param conversionService
     */
    public void CdDeserializer.setConversionService(ConversionService conversionService) {
        this.conversionService = conversionService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param jsonParser
     * @param context
     * @param codec
     * @param tree
     * @return Cd
     * @throws IOException
     */
    public Cd CdDeserializer.deserializeObject(JsonParser jsonParser, DeserializationContext context, ObjectCodec codec, JsonNode tree) throws IOException {
        String idText = tree.asText();
        Long id = conversionService.convert(idText, Long.class);
        Cd cd = cdService.findOne(id);
        if (cd == null) {
            throw new NotFoundException("Cd not found");
        }
        return cd;
    }
    
}
