// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dik.roo.collmate.web;

import dik.roo.collmate.domain.Cd;
import dik.roo.collmate.service.api.CdService;
import dik.roo.collmate.web.CdsCollectionJsonController;
import dik.roo.collmate.web.CdsItemJsonController;
import io.springlets.data.domain.GlobalSearch;
import java.util.Collection;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.mvc.method.annotation.MvcUriComponentsBuilder;
import org.springframework.web.util.UriComponents;

privileged aspect CdsCollectionJsonController_Roo_JSON {
    
    declare @type: CdsCollectionJsonController: @RestController;
    
    declare @type: CdsCollectionJsonController: @RequestMapping(value = "/rest/cds", name = "CdsCollectionJsonController", produces = MediaType.APPLICATION_JSON_VALUE);
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private CdService CdsCollectionJsonController.cdService;
    
    /**
     * TODO Auto-generated constructor documentation
     * 
     * @param cdService
     */
    @Autowired
    public CdsCollectionJsonController.new(CdService cdService) {
        this.cdService = cdService;
    }

    /**
     * TODO Auto-generated method documentation
     * 
     * @return CdService
     */
    public CdService CdsCollectionJsonController.getCdService() {
        return cdService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param cdService
     */
    public void CdsCollectionJsonController.setCdService(CdService cdService) {
        this.cdService = cdService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param globalSearch
     * @param pageable
     * @return ResponseEntity
     */
    @GetMapping(name = "list")
    public ResponseEntity<Page<Cd>> CdsCollectionJsonController.list(GlobalSearch globalSearch, Pageable pageable) {
        
        Page<Cd> cds = getCdService().findAll(globalSearch, pageable);
        return ResponseEntity.ok(cds);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return UriComponents
     */
    public static UriComponents CdsCollectionJsonController.listURI() {
        return MvcUriComponentsBuilder
            .fromMethodCall(
                MvcUriComponentsBuilder.on(CdsCollectionJsonController.class).list(null, null))
            .build().encode();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param cd
     * @param result
     * @return ResponseEntity
     */
    @PostMapping(name = "create")
    public ResponseEntity<?> CdsCollectionJsonController.create(@Valid @RequestBody Cd cd, BindingResult result) {
        
        if (cd.getId() != null || cd.getVersion() != null) {        
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
        
        if (result.hasErrors()) {
            return ResponseEntity.status(HttpStatus.CONFLICT).body(result);
        }
        
        Cd newCd = getCdService().save(cd);
        UriComponents showURI = CdsItemJsonController.showURI(newCd);
        
        return ResponseEntity.created(showURI.toUri()).build();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param cds
     * @param result
     * @return ResponseEntity
     */
    @PostMapping(value = "/batch", name = "createBatch")
    public ResponseEntity<?> CdsCollectionJsonController.createBatch(@Valid @RequestBody Collection<Cd> cds, BindingResult result) {
        
        if (result.hasErrors()) {
            return ResponseEntity.status(HttpStatus.CONFLICT).body(result);
        }
        
        getCdService().save(cds);
        
        return ResponseEntity.created(listURI().toUri()).build();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param cds
     * @param result
     * @return ResponseEntity
     */
    @PutMapping(value = "/batch", name = "updateBatch")
    public ResponseEntity<?> CdsCollectionJsonController.updateBatch(@Valid @RequestBody Collection<Cd> cds, BindingResult result) {
        
        if (result.hasErrors()) {
            return ResponseEntity.status(HttpStatus.CONFLICT).body(result);
        }
        
        getCdService().save(cds);
        
        return ResponseEntity.ok().build();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param ids
     * @return ResponseEntity
     */
    @DeleteMapping(value = "/batch/{ids}", name = "deleteBatch")
    public ResponseEntity<?> CdsCollectionJsonController.deleteBatch(@PathVariable("ids") Collection<Long> ids) {
        
        getCdService().delete(ids);
        
        return ResponseEntity.ok().build();
    }
    
}
