// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dik.roo.collmate.web;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.ObjectCodec;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import dik.roo.collmate.domain.Dvd;
import dik.roo.collmate.service.api.DvdService;
import dik.roo.collmate.web.DvdDeserializer;
import io.springlets.web.NotFoundException;
import java.io.IOException;
import org.springframework.boot.jackson.JsonComponent;
import org.springframework.core.convert.ConversionService;

privileged aspect DvdDeserializer_Roo_EntityDeserializer {
    
    declare @type: DvdDeserializer: @JsonComponent;
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return DvdService
     */
    public DvdService DvdDeserializer.getDvdService() {
        return dvdService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param dvdService
     */
    public void DvdDeserializer.setDvdService(DvdService dvdService) {
        this.dvdService = dvdService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return ConversionService
     */
    public ConversionService DvdDeserializer.getConversionService() {
        return conversionService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param conversionService
     */
    public void DvdDeserializer.setConversionService(ConversionService conversionService) {
        this.conversionService = conversionService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param jsonParser
     * @param context
     * @param codec
     * @param tree
     * @return Dvd
     * @throws IOException
     */
    public Dvd DvdDeserializer.deserializeObject(JsonParser jsonParser, DeserializationContext context, ObjectCodec codec, JsonNode tree) throws IOException {
        String idText = tree.asText();
        Long id = conversionService.convert(idText, Long.class);
        Dvd dvd = dvdService.findOne(id);
        if (dvd == null) {
            throw new NotFoundException("Dvd not found");
        }
        return dvd;
    }
    
}
