// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dik.roo.collmate.web;

import dik.roo.collmate.domain.Dvd;
import dik.roo.collmate.domain.reference.Status;
import dik.roo.collmate.service.api.DvdService;
import dik.roo.collmate.web.DvdsCollectionThymeleafController;
import dik.roo.collmate.web.DvdsItemThymeleafController;
import dik.roo.collmate.web.DvdsItemThymeleafLinkFactory;
import io.springlets.data.web.validation.GenericValidator;
import io.springlets.web.NotFoundException;
import io.springlets.web.mvc.util.ControllerMethodLinkBuilderFactory;
import io.springlets.web.mvc.util.MethodLinkBuilderFactory;
import io.springlets.web.mvc.util.concurrency.ConcurrencyCallback;
import io.springlets.web.mvc.util.concurrency.ConcurrencyManager;
import io.springlets.web.mvc.util.concurrency.ConcurrencyTemplate;
import java.util.Arrays;
import java.util.Locale;
import javax.validation.Valid;
import org.joda.time.format.DateTimeFormat;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.MessageSource;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.WebDataBinder;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.InitBinder;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.util.UriComponents;

privileged aspect DvdsItemThymeleafController_Roo_Thymeleaf {
    
    declare @type: DvdsItemThymeleafController: @Controller;
    
    declare @type: DvdsItemThymeleafController: @RequestMapping(value = "/dvds/{dvd}", name = "DvdsItemThymeleafController", produces = MediaType.TEXT_HTML_VALUE);
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private DvdService DvdsItemThymeleafController.dvdService;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private MessageSource DvdsItemThymeleafController.messageSource;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private MethodLinkBuilderFactory<DvdsItemThymeleafController> DvdsItemThymeleafController.itemLink;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private MethodLinkBuilderFactory<DvdsCollectionThymeleafController> DvdsItemThymeleafController.collectionLink;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private final ConcurrencyTemplate<Dvd> DvdsItemThymeleafController.concurrencyTemplate = new ConcurrencyTemplate<Dvd>(this);
    
    /**
     * TODO Auto-generated constructor documentation
     * 
     * @param dvdService
     * @param messageSource
     * @param linkBuilder
     */
    @Autowired
    public DvdsItemThymeleafController.new(DvdService dvdService, MessageSource messageSource, ControllerMethodLinkBuilderFactory linkBuilder) {
        setDvdService(dvdService);
        setMessageSource(messageSource);
        setItemLink(linkBuilder.of(DvdsItemThymeleafController.class));
        setCollectionLink(linkBuilder.of(DvdsCollectionThymeleafController.class));
    }

    /**
     * TODO Auto-generated method documentation
     * 
     * @return DvdService
     */
    public DvdService DvdsItemThymeleafController.getDvdService() {
        return dvdService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param dvdService
     */
    public void DvdsItemThymeleafController.setDvdService(DvdService dvdService) {
        this.dvdService = dvdService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return MessageSource
     */
    public MessageSource DvdsItemThymeleafController.getMessageSource() {
        return messageSource;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param messageSource
     */
    public void DvdsItemThymeleafController.setMessageSource(MessageSource messageSource) {
        this.messageSource = messageSource;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return MethodLinkBuilderFactory
     */
    public MethodLinkBuilderFactory<DvdsItemThymeleafController> DvdsItemThymeleafController.getItemLink() {
        return itemLink;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param itemLink
     */
    public void DvdsItemThymeleafController.setItemLink(MethodLinkBuilderFactory<DvdsItemThymeleafController> itemLink) {
        this.itemLink = itemLink;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return MethodLinkBuilderFactory
     */
    public MethodLinkBuilderFactory<DvdsCollectionThymeleafController> DvdsItemThymeleafController.getCollectionLink() {
        return collectionLink;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param collectionLink
     */
    public void DvdsItemThymeleafController.setCollectionLink(MethodLinkBuilderFactory<DvdsCollectionThymeleafController> collectionLink) {
        this.collectionLink = collectionLink;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param id
     * @param locale
     * @param method
     * @return Dvd
     */
    @ModelAttribute
    public Dvd DvdsItemThymeleafController.getDvd(@PathVariable("dvd") Long id, Locale locale, HttpMethod method) {
        Dvd dvd = null;
        if (HttpMethod.PUT.equals(method)) {
            dvd = dvdService.findOneForUpdate(id);
        } else {
            dvd = dvdService.findOne(id);
        }
        
        if (dvd == null) {
            String message = messageSource.getMessage("error_NotFound", new Object[] {"Dvd", id}, "The record couldn't be found", locale);
            throw new NotFoundException(message);
        }
        return dvd;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param dvd
     * @param model
     * @return ModelAndView
     */
    @GetMapping(name = "show")
    public ModelAndView DvdsItemThymeleafController.show(@ModelAttribute Dvd dvd, Model model) {
        model.addAttribute("dvd", dvd);
        return new ModelAndView("dvds/show");
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param dvd
     * @param model
     * @return ModelAndView
     */
    @GetMapping(value = "/inline", name = "showInline")
    public ModelAndView DvdsItemThymeleafController.showInline(@ModelAttribute Dvd dvd, Model model) {
        model.addAttribute("dvd", dvd);
        return new ModelAndView("dvds/showInline :: inline-content");
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param model
     */
    public void DvdsItemThymeleafController.populateFormats(Model model) {
        model.addAttribute("application_locale", LocaleContextHolder.getLocale().getLanguage());
        model.addAttribute("added_date_format", DateTimeFormat.patternForStyle("M-", LocaleContextHolder.getLocale()));
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param model
     */
    public void DvdsItemThymeleafController.populateForm(Model model) {
        populateFormats(model);
        model.addAttribute("status", Arrays.asList(Status.values()));
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return ConcurrencyTemplate
     */
    public ConcurrencyTemplate<Dvd> DvdsItemThymeleafController.getConcurrencyTemplate() {
        return concurrencyTemplate;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return String
     */
    public String DvdsItemThymeleafController.getModelName() {
        return "dvd";
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return String
     */
    public String DvdsItemThymeleafController.getEditViewPath() {
        return "dvds/edit";
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param record
     * @return Integer
     */
    public Integer DvdsItemThymeleafController.getLastVersion(Dvd record) {
        return getDvdService().findOne(record.getId()).getVersion();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param entity
     * @param model
     * @return ModelAndView
     */
    public ModelAndView DvdsItemThymeleafController.populateAndGetFormView(Dvd entity, Model model) {
        // Populate the form with all the necessary elements
        populateForm(model);
        // Add concurrency attribute to the model to show the concurrency form
        // in the current edit view
        model.addAttribute("concurrency", true);
        // Add the new version value to the model.
        model.addAttribute("newVersion", getLastVersion(entity));
        // Add the current pet values to maintain the values introduced by the user
        model.addAttribute(getModelName(), entity);
        // Return the edit view path
        return new org.springframework.web.servlet.ModelAndView(getEditViewPath(), model.asMap());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param binder
     */
    @InitBinder("dvd")
    public void DvdsItemThymeleafController.initDvdBinder(WebDataBinder binder) {
        binder.setDisallowedFields("id");
        // Register validators
        GenericValidator validator = new GenericValidator(Dvd.class, getDvdService());
        binder.addValidators(validator);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param dvd
     * @param model
     * @return ModelAndView
     */
    @GetMapping(value = "/edit-form", name = "editForm")
    public ModelAndView DvdsItemThymeleafController.editForm(@ModelAttribute Dvd dvd, Model model) {
        populateForm(model);
        
        model.addAttribute("dvd", dvd);
        return new ModelAndView("dvds/edit");
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param dvd
     * @param result
     * @param version
     * @param concurrencyControl
     * @param model
     * @return ModelAndView
     */
    @PutMapping(name = "update")
    public ModelAndView DvdsItemThymeleafController.update(@Valid @ModelAttribute Dvd dvd, BindingResult result, @RequestParam("version") Integer version, @RequestParam(value = "concurrency", required = false, defaultValue = "") String concurrencyControl, Model model) {
        // Check if provided form contain errors
        if (result.hasErrors()) {
            populateForm(model);
            return new ModelAndView(getEditViewPath());
        }
        // Create Concurrency Spring Template to ensure that the following code will manage the
        // possible concurrency exceptions that appears and execute the provided coded inside the Spring template.
        // If some concurrency exception appears the template will manage it.
        Dvd savedDvd = getConcurrencyTemplate().execute(dvd, model, new ConcurrencyCallback<Dvd>() {
            @Override
            public Dvd doInConcurrency(Dvd dvd) throws Exception {
                return getDvdService().save(dvd);
            }
        });
        UriComponents showURI = getItemLink().to(DvdsItemThymeleafLinkFactory.SHOW).with("dvd", savedDvd.getId()).toUri();
        return new ModelAndView("redirect:" + showURI.toUriString());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param dvd
     * @return ResponseEntity
     */
    @ResponseBody
    @DeleteMapping(name = "delete")
    public ResponseEntity<?> DvdsItemThymeleafController.delete(@ModelAttribute Dvd dvd) {
        getDvdService().delete(dvd);
        return ResponseEntity.ok().build();
    }
    
}
