// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dik.roo.collmate.web;

import dik.roo.collmate.domain.Dvd;
import dik.roo.collmate.service.api.DvdService;
import dik.roo.collmate.web.DvdsCollectionJsonController;
import dik.roo.collmate.web.DvdsItemJsonController;
import io.springlets.data.domain.GlobalSearch;
import java.util.Collection;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.mvc.method.annotation.MvcUriComponentsBuilder;
import org.springframework.web.util.UriComponents;

privileged aspect DvdsCollectionJsonController_Roo_JSON {
    
    declare @type: DvdsCollectionJsonController: @RestController;
    
    declare @type: DvdsCollectionJsonController: @RequestMapping(value = "/rest/dvds", name = "DvdsCollectionJsonController", produces = MediaType.APPLICATION_JSON_VALUE);
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private DvdService DvdsCollectionJsonController.dvdService;
    
    /**
     * TODO Auto-generated constructor documentation
     * 
     * @param dvdService
     */
    @Autowired
    public DvdsCollectionJsonController.new(DvdService dvdService) {
        this.dvdService = dvdService;
    }

    /**
     * TODO Auto-generated method documentation
     * 
     * @return DvdService
     */
    public DvdService DvdsCollectionJsonController.getDvdService() {
        return dvdService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param dvdService
     */
    public void DvdsCollectionJsonController.setDvdService(DvdService dvdService) {
        this.dvdService = dvdService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param globalSearch
     * @param pageable
     * @return ResponseEntity
     */
    @GetMapping(name = "list")
    public ResponseEntity<Page<Dvd>> DvdsCollectionJsonController.list(GlobalSearch globalSearch, Pageable pageable) {
        
        Page<Dvd> dvds = getDvdService().findAll(globalSearch, pageable);
        return ResponseEntity.ok(dvds);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return UriComponents
     */
    public static UriComponents DvdsCollectionJsonController.listURI() {
        return MvcUriComponentsBuilder
            .fromMethodCall(
                MvcUriComponentsBuilder.on(DvdsCollectionJsonController.class).list(null, null))
            .build().encode();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param dvd
     * @param result
     * @return ResponseEntity
     */
    @PostMapping(name = "create")
    public ResponseEntity<?> DvdsCollectionJsonController.create(@Valid @RequestBody Dvd dvd, BindingResult result) {
        
        if (dvd.getId() != null || dvd.getVersion() != null) {        
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
        
        if (result.hasErrors()) {
            return ResponseEntity.status(HttpStatus.CONFLICT).body(result);
        }
        
        Dvd newDvd = getDvdService().save(dvd);
        UriComponents showURI = DvdsItemJsonController.showURI(newDvd);
        
        return ResponseEntity.created(showURI.toUri()).build();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param dvds
     * @param result
     * @return ResponseEntity
     */
    @PostMapping(value = "/batch", name = "createBatch")
    public ResponseEntity<?> DvdsCollectionJsonController.createBatch(@Valid @RequestBody Collection<Dvd> dvds, BindingResult result) {
        
        if (result.hasErrors()) {
            return ResponseEntity.status(HttpStatus.CONFLICT).body(result);
        }
        
        getDvdService().save(dvds);
        
        return ResponseEntity.created(listURI().toUri()).build();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param dvds
     * @param result
     * @return ResponseEntity
     */
    @PutMapping(value = "/batch", name = "updateBatch")
    public ResponseEntity<?> DvdsCollectionJsonController.updateBatch(@Valid @RequestBody Collection<Dvd> dvds, BindingResult result) {
        
        if (result.hasErrors()) {
            return ResponseEntity.status(HttpStatus.CONFLICT).body(result);
        }
        
        getDvdService().save(dvds);
        
        return ResponseEntity.ok().build();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param ids
     * @return ResponseEntity
     */
    @DeleteMapping(value = "/batch/{ids}", name = "deleteBatch")
    public ResponseEntity<?> DvdsCollectionJsonController.deleteBatch(@PathVariable("ids") Collection<Long> ids) {
        
        getDvdService().delete(ids);
        
        return ResponseEntity.ok().build();
    }
    
}
