// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dik.roo.collmate.repository;

import com.querydsl.core.types.Path;
import com.querydsl.jpa.JPQLQuery;
import dik.roo.collmate.domain.Cd;
import dik.roo.collmate.domain.QCd;
import dik.roo.collmate.repository.CdRepositoryImpl;
import io.springlets.data.domain.GlobalSearch;
import io.springlets.data.jpa.repository.support.QueryDslRepositorySupportExt.AttributeMappingBuilder;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CdRepositoryImpl_Roo_Jpa_Repository_Impl {
    
    declare @type: CdRepositoryImpl: @Transactional(readOnly = true);
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String CdRepositoryImpl.NAME = "name";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String CdRepositoryImpl.PERFORMER = "performer";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String CdRepositoryImpl.RELEASE_YEAR = "releaseYear";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String CdRepositoryImpl.DISK_COUNT = "diskCount";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String CdRepositoryImpl.MEDIUM = "medium";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String CdRepositoryImpl.LABEL = "label";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String CdRepositoryImpl.STATUS = "status";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String CdRepositoryImpl.ADDED = "added";
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param globalSearch
     * @param pageable
     * @return Page
     */
    public Page<Cd> CdRepositoryImpl.findAll(GlobalSearch globalSearch, Pageable pageable) {
        
        QCd cd = QCd.cd;
        
        JPQLQuery<Cd> query = from(cd);
        
        Path<?>[] paths = new Path<?>[] {cd.name,cd.performer,cd.releaseYear,cd.diskCount,cd.medium,cd.label,cd.status,cd.added};        
        applyGlobalSearch(globalSearch, query, paths);
        
        AttributeMappingBuilder mapping = buildMapper()
			.map(NAME, cd.name)
			.map(PERFORMER, cd.performer)
			.map(RELEASE_YEAR, cd.releaseYear)
			.map(DISK_COUNT, cd.diskCount)
			.map(MEDIUM, cd.medium)
			.map(LABEL, cd.label)
			.map(STATUS, cd.status)
			.map(ADDED, cd.added);
        
        applyPagination(pageable, query, mapping);
        applyOrderById(query);
        
        return loadPage(query, pageable, cd);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param ids
     * @param globalSearch
     * @param pageable
     * @return Page
     */
    public Page<Cd> CdRepositoryImpl.findAllByIdsIn(List<Long> ids, GlobalSearch globalSearch, Pageable pageable) {
        
        QCd cd = QCd.cd;
        
        JPQLQuery<Cd> query = from(cd);
        
        Path<?>[] paths = new Path<?>[] {cd.name,cd.performer,cd.releaseYear,cd.diskCount,cd.medium,cd.label,cd.status,cd.added};        
        applyGlobalSearch(globalSearch, query, paths);
        
        // Also, filter by the provided ids
        query.where(cd.id.in(ids));
        
        AttributeMappingBuilder mapping = buildMapper()
			.map(NAME, cd.name)
			.map(PERFORMER, cd.performer)
			.map(RELEASE_YEAR, cd.releaseYear)
			.map(DISK_COUNT, cd.diskCount)
			.map(MEDIUM, cd.medium)
			.map(LABEL, cd.label)
			.map(STATUS, cd.status)
			.map(ADDED, cd.added);
        
        applyPagination(pageable, query, mapping);
        applyOrderById(query);
        
        return loadPage(query, pageable, cd);
    }
    
}
