// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dik.roo.collmate.repository;

import dik.roo.collmate.repository.CdRepository;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CdRepository_Roo_Jpa_Repository {
    
    declare @type: CdRepository: @Transactional(readOnly = true);
    
}
