// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dik.roo.collmate.domain.dod;

import dik.roo.collmate.domain.dod.CdDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CdDataOnDemand_Roo_Configurable {
    
    declare @type: CdDataOnDemand: @Configurable;
    
}
