// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dik.roo.collmate.domain.dod;

import dik.roo.collmate.domain.Cd;
import dik.roo.collmate.domain.dod.CdFactory;
import dik.roo.collmate.domain.reference.Status;
import java.util.Calendar;
import java.util.GregorianCalendar;

privileged aspect CdFactory_Roo_JpaEntityFactory {
    
    /**
     * Creates a new {@link Cd} with the given index.
     * 
     * @param index position of the Cd
     * @return a new transient Cd
     */
    public Cd CdFactory.create(int index) {
        Cd obj = new Cd();
        setAdded(obj, index);
        setDiskCount(obj, index);
        setLabel(obj, index);
        setMedium(obj, index);
        setName(obj, index);
        setPerformer(obj, index);
        setReleaseYear(obj, index);
        setStatus(obj, index);
        return obj;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CdFactory.setAdded(Cd obj, int index) {
        Calendar added = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), 
			Calendar.getInstance().get(Calendar.MONTH), 
			Calendar.getInstance().get(Calendar.DAY_OF_MONTH) - 1);
        obj.setAdded(added);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CdFactory.setDiskCount(Cd obj, int index) {
        String diskCount = "diskCount_" + index;
        obj.setDiskCount(diskCount);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CdFactory.setLabel(Cd obj, int index) {
        String label = "label_" + index;
        obj.setLabel(label);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CdFactory.setMedium(Cd obj, int index) {
        String medium = "medium_" + index;
        obj.setMedium(medium);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CdFactory.setName(Cd obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CdFactory.setPerformer(Cd obj, int index) {
        String performer = "performer_" + index;
        obj.setPerformer(performer);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CdFactory.setReleaseYear(Cd obj, int index) {
        String releaseYear = "releaseYear_" + index;
        obj.setReleaseYear(releaseYear);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CdFactory.setStatus(Cd obj, int index) {
        Status status = Status.class.getEnumConstants()[0];
        obj.setStatus(status);
    }
    
}
