// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dik.roo.collmate.domain;

import dik.roo.collmate.domain.CdTest;
import dik.roo.collmate.domain.dod.CdFactory;

privileged aspect CdTest_Roo_JpaUnitTest {
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private CdFactory CdTest.cdFactory = new CdFactory();
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return CdFactory
     */
    public CdFactory CdTest.getCdFactory() {
        return cdFactory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param cdFactory
     */
    public void CdTest.setCdFactory(CdFactory cdFactory) {
        this.cdFactory = cdFactory;
    }
    
}
