// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dik.roo.collmate.domain;

import dik.roo.collmate.domain.DvdTest;
import dik.roo.collmate.domain.dod.DvdFactory;

privileged aspect DvdTest_Roo_JpaUnitTest {
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private DvdFactory DvdTest.dvdFactory = new DvdFactory();
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return DvdFactory
     */
    public DvdFactory DvdTest.getDvdFactory() {
        return dvdFactory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param dvdFactory
     */
    public void DvdTest.setDvdFactory(DvdFactory dvdFactory) {
        this.dvdFactory = dvdFactory;
    }
    
}
