// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dik.roo.collmate.repository;

import static org.assertj.core.api.Assertions.assertThat;

import dik.roo.collmate.config.SpringDataJpaDetachableRepositoryConfiguration;
import dik.roo.collmate.dod.DataOnDemandConfiguration;
import dik.roo.collmate.domain.Dvd;
import dik.roo.collmate.domain.dod.DvdDataOnDemand;
import dik.roo.collmate.repository.DvdRepository;
import dik.roo.collmate.repository.DvdRepositoryIT;
import io.springlets.data.domain.GlobalSearch;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.context.annotation.Import;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.test.context.junit4.SpringRunner;

privileged aspect DvdRepositoryIT_Roo_RepositoryJpaIntegrationTest {
    
    declare @type: DvdRepositoryIT: @RunWith(SpringRunner.class);
    
    declare @type: DvdRepositoryIT: @DataJpaTest;
    
    declare @type: DvdRepositoryIT: @Import({ DataOnDemandConfiguration.class, SpringDataJpaDetachableRepositoryConfiguration.class });
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @Rule
    public ExpectedException DvdRepositoryIT.thrown = ExpectedException.none();
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @Autowired
    private DvdRepository DvdRepositoryIT.repository;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @Autowired
    private DvdDataOnDemand DvdRepositoryIT.dod;
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return DvdRepository
     */
    public DvdRepository DvdRepositoryIT.getRepository() {
        return repository;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return DvdDataOnDemand
     */
    public DvdDataOnDemand DvdRepositoryIT.getDod() {
        return dod;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Before
    public void DvdRepositoryIT.checkDataOnDemandHasInitializedCorrectly() {
        assertThat(getDod().getRandomDvd())
            .as("Check data on demand for 'Dvd' initializes correctly by getting a random Dvd")
            .isNotNull();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void DvdRepositoryIT.countShouldReturnExpectedValue() {
        // Verify
        assertThat(getRepository().count()).as("Check there are available 'Dvd' entries").isGreaterThan(0);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void DvdRepositoryIT.findOneShouldReturnExistingDvd() {
        // Setup
        Long id = getRandomDvdId();
        
        // Exercise
        Dvd dvd = getRepository().findOne(id);
        
        // Verify
        assertThat(dvd).as("Check that findOne illegally returned null for id %s", id).isNotNull();
        assertThat(id).as("Check the identifier of the found 'Dvd' is the same used to look for it")
            .isEqualTo(dvd.getId());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void DvdRepositoryIT.findAllShouldReturnAllDvds() {
        // Setup
        assertThat(getRepository().count())
            .as("Check the number of entries is not too big (250 entries). "
                + "If it is, please review the tests so it doesn't take too long to run them")
            .isLessThan(250);
        
        // Exercise
        List<Dvd> result = getRepository().findAll();
        
        // Verify
        assertThat(result).as("Check 'findAll' returns a not null list of entries").isNotNull();
        assertThat(result.size()).as("Check 'findAll' returns a not empty list of entries")
            .isGreaterThan(0);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void DvdRepositoryIT.persistShouldGenerateIdValue() {
        // Setup
        // Exercise
        Dvd dvd = getDod().getNewRandomTransientDvd();
        
        // Verify
        assertThat(dvd).as("Check the Data on demand generated a new non null 'Dvd'").isNotNull();
        assertThat(dvd.getId()).as("Check the Data on demand generated a new 'Dvd' whose id is null")
            .isNull();
        try {
            dvd = getRepository().saveAndFlush(dvd);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter
                .hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".")
                    .append(cv.getPropertyPath()).append(": ").append(cv.getMessage())
                    .append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        assertThat(dvd.getId()).as("Check a 'Dvd' (%s) id is not null after been persisted", dvd)
            .isNotNull();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void DvdRepositoryIT.deleteShouldMakeDvdUnavailable() {
        // Setup
        Long id = getRandomDvdId();
        Dvd dvd = getRepository().findOne(id);
        
        // Exercise
        getRepository().delete(dvd);
        
        // Verify
        assertThat(getRepository().findOne(id))
        .as("Check the deleted 'Dvd' %s is no longer available with 'findOne'", dvd).isNull();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void DvdRepositoryIT.findAllCustomNotFilteredNotPagedShouldReturnAllDvds() {
        // Exercise
        Page<Dvd> all = getRepository().findAll((GlobalSearch) null, new PageRequest(0, getDod().getSize()));
        
        // Verify
        assertThat(all.getNumberOfElements())
            .as("Check 'findAll' with null 'GlobalSearch' and no pagination returns all entries")
            .isEqualTo(getDod().getSize());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void DvdRepositoryIT.findAllCustomNotFilteredPagedShouldReturnADvdsPage() {
        // Exercise
        Page<Dvd> all = getRepository().findAll((GlobalSearch) null, new PageRequest(0, 3));
        
        // Verify
        assertThat(all.getNumberOfElements())
            .as("Check result number is not greater than the page size").isLessThanOrEqualTo(3);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Long
     */
    private Long DvdRepositoryIT.getRandomDvdId() {
        Dvd dvd = getDod().getRandomDvd();
        Long id = dvd.getId();
        assertThat(id).as("Check the Data on demand generated a 'Dvd' with an identifier").isNotNull();
        return id;
    }
    
}
